<a href="https://colab.research.google.com/github/Rose-Petals/TOL-1B/blob/main/Tree_of_Life_Project_Team_B_dataset3clean.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tree of Life Plan Team B**

## Load Data

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/Rose-Petals/TOL-1B/main/TOLCC%20Break%20Through%20Tech%20Dataset%20(1).csv"

df = pd.read_csv(url)

print(df.head())

  INTAKE METHOD        REFERENCES  \
0          Call  Bariatric Doctor
1          Call     Family/Friend
2     Boom Form     Family/Friend
3     Boom Form     Family/Friend
4     Boom Form     Family/Friend

  Please be specific on who sent you our way, we'd like to thank them.   \
0                                   Bariatric Doctor
1                                                Mom
2                                             Friend
3                                                NaN
4                                                NaN

     AGE       TOWN  INSURANCE CARRIER APPOINTMENT LOCATION APPOINTMENT TYPE  \
0  25-30  Elizabeth               BCBS              Virtual     Talk Therapy
1  10-15     Summit  United Healthcare              Virtual     Talk Therapy
2  20-25     Monroe               BCBS             Freehold     Talk Therapy
3  25-30      Ocean               BCBS             Freehold     Talk Therapy
4  30-35    Jackson              Aetna             Freehold     Talk Therapy

  If Talk Therapy, specifically what type?  Appointment Time  ... Unnamed: 17  \
0                     Bariatric Evaluation     Evening (4-8)  ...         NaN
1                       Individual (minor)  Afternoon (12-4)  ...         NaN
2                       Individual (adult)  Afternoon (12-4)  ...         NaN
3                       Individual (adult)  Afternoon (12-4)  ...         NaN
4                       Individual (adult)  Afternoon (12-4)  ...         NaN

   Unnamed: 18  Unnamed: 19  Unnamed: 20  Unnamed: 21  Unnamed: 22  \
0          NaN          NaN          NaN          NaN          NaN
1          NaN          NaN          NaN          NaN          NaN
2          NaN          NaN          NaN          NaN          NaN
3          NaN          NaN          NaN          NaN          NaN
4          NaN          NaN          NaN          NaN          NaN

   Unnamed: 23  Unnamed: 24  Unnamed: 25  Unnamed: 26
0          NaN          NaN          NaN          NaN
1          NaN          NaN          NaN          NaN
2          NaN          NaN          NaN          NaN
3          NaN          NaN          NaN          NaN
4          NaN          NaN          NaN          NaN

[5 rows x 27 columns]

## Data Cleaning

### Removing and Renaming Columns

In [ ]:
df = df.drop(columns=[col for col in df.columns if "Unnamed" in col])
df = df.drop(columns=["Please be specific on who sent you our way, we'd like to thank them. "])
print(df.columns)

Index(['INTAKE METHOD', ' REFERENCES', 'AGE', 'TOWN', 'INSURANCE CARRIER',
       'APPOINTMENT LOCATION', 'APPOINTMENT TYPE',
       'If Talk Therapy, specifically what type?', 'Appointment Time'],
      dtype='object')

In [ ]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

print(df.columns)

Index(['intake_method', 'references', 'age', 'town', 'insurance_carrier',
       'appointment_location', 'appointment_type',
       'if_talk_therapy,_specifically_what_type?', 'appointment_time'],
      dtype='object')

In [ ]:
df.rename(columns={'if_talk_therapy,_specifically_what_type?': 'talk_therapy_type'}, inplace=True)
df.columns

Index(['intake_method', 'references', 'age', 'town', 'insurance_carrier',
       'appointment_location', 'appointment_type', 'talk_therapy_type',
       'appointment_time'],
      dtype='object')

### Handling Missing Values

In [ ]:
print(df.isnull().sum())

intake_method             0
references                2
age                       6
town                      4
insurance_carrier         2
appointment_location      1
appointment_type          1
talk_therapy_type       105
appointment_time          1
dtype: int64

In [ ]:
df['talk_therapy_type'] = df['talk_therapy_type'].fillna("not_talk_therapy")
print(df.isnull().sum())

intake_method           0
references              2
age                     6
town                    4
insurance_carrier       2
appointment_location    1
appointment_type        1
talk_therapy_type       0
appointment_time        1
dtype: int64

In [ ]:
# Column Types
df.dtypes

intake_method           object
references              object
age                     object
town                    object
insurance_carrier       object
appointment_location    object
appointment_type        object
talk_therapy_type       object
appointment_time        object
dtype: object

In [ ]:
# 'age' is a categorical variable with nan values.
print("Number of unique categories for 'age' column : ", df['age'].nunique())
print()
print(df['age'].unique())

Number of unique categories for 'age' column :  44

['25-30' '10-15' '20-25' '30-35' nan '15-20' '60-65' '40-45' '1-5' '5-10'
 '50-55' '55-60' '35-40' '65-70' '35-40; 35-40' '50-55; 45-50'
 '25-30; 30-35' '50-55; 50-55' '30-35; 40-45' '30-35; 30-35'
 '45-50; 40-45' '55--60' '75-80' '70-75' '80-85' '85-90' '35-40; 40-45'
 '65-70; 65-70' '40-45; 50-55' '55-60; 55-60' '25-20' '45-50; 45-50'
 '60-65; 55-60' '55-60; 60-65' '45-50' '30-35; 25-30' '40-45; 35-40'
 '25-30; 25-30' '40-45; 40-45' '55-60; 50-55' '35-40; 30-35'
 '60-65; 60-65' '25-30; 20-25' '30-35; 35-40' '45-50; 50-55']

###### The 'appointment_time' column is our column of interest. So, remove the row with a missing value for 'appointment time.

In [ ]:
print("Number of rows in df before drop : ", df.shape[0])
print()
print(df[df['appointment_time'].isnull()])
to_remove_index = df[df['appointment_time'].isnull()].index
df.drop(to_remove_index, inplace = True)
print()
print("Number of rows in df after drop: ", df.shape[0])

Number of rows in df before drop :  1035

     intake_method     references    age         town insurance_carrier  \
1034     Boom Form  Family/Friend  20-25  Union Beach             Aetna

     appointment_location appointment_type talk_therapy_type appointment_time
1034                  NaN              NaN  not_talk_therapy              NaN

Number of rows in df after drop:  1034

In [ ]:
# Replacing missing values in the other categorical variables with 'Unknown'
categorical_cols = ['references', 'age', 'town', 'insurance_carrier', 'appointment_location', 'appointment_type']

for col in categorical_cols:
  df[col] = df[col].fillna("Unknown")

print(df.isnull().sum())

intake_method           0
references              0
age                     0
town                    0
insurance_carrier       0
appointment_location    0
appointment_type        0
talk_therapy_type       0
appointment_time        0
dtype: int64

In [ ]:
# Number of unique values in each column
df.nunique()

intake_method             4
references               13
age                      45
town                    191
insurance_carrier        17
appointment_location      3
appointment_type          2
talk_therapy_type         7
appointment_time          3
dtype: int64

# Load Dataset 3

In [9]:
import pandas as pd

url_dataset3 = "https://raw.githubusercontent.com/Rose-Petals/TOL-1B/main/TOLCC%20Break%20Through%20Tech%20Dataset_3.csv"
df3 = pd.read_csv(url_dataset3)
display(df3.head())

,Intake Method,Lead Source,"Referring Provider Name (If other, please specify)",Age,Appointment Location,Appointment Type,Preferred Appointment Time
0,Boom,Insurance Company,NaN,40-45,Princeton,Medication Management,Evening (4p-8p)
1,Boom,Healthcare Provider,HLOC,25-30,Princeton,Talk Therapy,Evening (4p-8p)
2,Boom,Google or another search engine,NaN,15-20,Freehold,Talk Therapy,Afternoon (12p-4p)
3,Boom,Insurance Company,PCP,25-30,Virtual,Talk Therapy,Evening (4p-8p)
4,Boom,Family/Friend,NaN,30-35,Freehold,Talk Therapy,Morning (9a-12p)

### Examining Categorical Variables in Dataset 3

In [3]:
display(df3.info())
display(df3.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233 entries, 0 to 232
Data columns (total 7 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   Intake Method                                       232 non-null    object
 1   Lead Source                                         233 non-null    object
 2   Referring Provider Name (If other, please specify)  30 non-null     object
 3   Age                                                 228 non-null    object
 4   Appointment Location                                231 non-null    object
 5   Appointment Type                                    231 non-null    object
 6   Preferred Appointment Time                          231 non-null    object
dtypes: object(7)
memory usage: 12.9+ KB

None

Intake Method                                           1
Lead Source                                             0
Referring Provider Name (If other, please specify)    203
Age                                                     5
Appointment Location                                    2
Appointment Type                                        2
Preferred Appointment Time                              2
dtype: int64

### Handling Missing Values and Cleaning Column Names for Dataset 3

In [4]:
# Fill missing values in 'Referring Provider Name (If other, please specify)' with 'Unknown'
df3['Referring Provider Name (If other, please specify)'] = df3['Referring Provider Name (If other, please specify)'].fillna('Unknown')

# Drop rows where 'Preferred Appointment Time' is missing
df3.dropna(subset=['Preferred Appointment Time'], inplace=True)

# Check missing values
display(df3.isnull().sum())

# Clean up column names
df3.columns = df3.columns.str.strip().str.lower().str.replace(" ", "_").str.replace("(", "").str.replace(")", "").str.replace(",", "").str.replace("if_other_please_specify", "")
display(df3.columns)

Intake Method                                         1
Lead Source                                           0
Referring Provider Name (If other, please specify)    0
Age                                                   4
Appointment Location                                  0
Appointment Type                                      2
Preferred Appointment Time                            0
dtype: int64

Index(['intake_method', 'lead_source', 'referring_provider_name_', 'age',
       'appointment_location', 'appointment_type',
       'preferred_appointment_time'],
      dtype='object')

In [5]:
# Check the number of unique values in each column
display(df3.nunique())

intake_method                  4
lead_source                   12
referring_provider_name_      10
age                           18
appointment_location           3
appointment_type               3
preferred_appointment_time     3
dtype: int64

### Reducing number of categories

##### Group some of the categories for columns like age and town that have a large number of unique categories.

# Compare new and old set

In [6]:
# function to group age ranges
def group_age(age):
    if pd.isna(age):
        return 'Unknown'
    elif '0-5' in age or '1-5' in age:
        return '0-5'
    elif '5-10' in age:
        return '5-10'
    elif '10-15' in age:
        return '10-15'
    elif '15-20' in age:
        return '15-20'
    elif '20-25' in age:
        return '20-25'
    elif '25-30' in age:
        return '25-30'
    elif '30-35' in age:
        return '30-35'
    elif '35-40' in age:
        return '35-40'
    elif '40-45' in age:
        return '40-45'
    elif '45-50' in age:
        return '45-50'
    elif '50-55' in age:
        return '50-55'
    elif '55-60' in age:
        return '55-60'
    elif '60-65' in age:
        return '60-65'
    elif '65-70' in age:
        return '65-70'
    elif '70-75' in age:
        return '70-75'
    elif '75-80' in age:
        return '75-80'
    elif '80-85' in age:
        return '80-85'
    elif '85-90' in age:
        return '85-90'
    else:
        return 'Other'

# Apply grouping function to the 'age' column
df3['age'] = df3['age'].apply(group_age)

# Check number of unique categories after grouping
display(df3['age'].nunique())
display(df3['age'].unique())

16

array(['40-45', '25-30', '15-20', '30-35', '35-40', '45-50', '0-5',
       'Unknown', '20-25', '55-60', '10-15', '5-10', 'Other', '80-85',
       '60-65', '65-70'], dtype=object)

In [7]:
# Reload the original dataset for comparison
url_dataset3 = "https://raw.githubusercontent.com/Rose-Petals/TOL-1B/main/TOLCC%20Break%20Through%20Tech%20Dataset_3.csv"
df3_original = pd.read_csv(url_dataset3)

print("Original DataFrame Head:")
display(df3_original.head())

print("\nCleaned DataFrame Head:")
display(df3.head())

Original DataFrame Head:

,Intake Method,Lead Source,"Referring Provider Name (If other, please specify)",Age,Appointment Location,Appointment Type,Preferred Appointment Time
0,Boom,Insurance Company,NaN,40-45,Princeton,Medication Management,Evening (4p-8p)
1,Boom,Healthcare Provider,HLOC,25-30,Princeton,Talk Therapy,Evening (4p-8p)
2,Boom,Google or another search engine,NaN,15-20,Freehold,Talk Therapy,Afternoon (12p-4p)
3,Boom,Insurance Company,PCP,25-30,Virtual,Talk Therapy,Evening (4p-8p)
4,Boom,Family/Friend,NaN,30-35,Freehold,Talk Therapy,Morning (9a-12p)

Cleaned DataFrame Head:

,intake_method,lead_source,referring_provider_name_,age,appointment_location,appointment_type,preferred_appointment_time
0,Boom,Insurance Company,Unknown,40-45,Princeton,Medication Management,Evening (4p-8p)
1,Boom,Healthcare Provider,HLOC,25-30,Princeton,Talk Therapy,Evening (4p-8p)
2,Boom,Google or another search engine,Unknown,15-20,Freehold,Talk Therapy,Afternoon (12p-4p)
3,Boom,Insurance Company,PCP,25-30,Virtual,Talk Therapy,Evening (4p-8p)
4,Boom,Family/Friend,Unknown,30-35,Freehold,Talk Therapy,Morning (9a-12p)

### Summary of Changes Made to Dataset 3

Here is a summary of the data cleaning steps applied to `df3`:

1.  **Handled Missing Values:**
    *   Filled missing values in the 'Referring Provider Name (If other, please specify)' column with 'Unknown'.
    *   Dropped rows where 'Preferred Appointment Time' was missing.
2.  **Cleaned Column Names:**
    *   Removed leading/trailing whitespace, converted to lowercase, replaced spaces with underscores, and removed special characters and the phrase "if other please specify" from column names.
3.  **Grouped Age Categories:**
    *   Grouped the various age ranges into broader categories for better analysis using the `group_age` function.