In [44]:
import pandas as pd
import numpy as np
import scipy.stats as stat

url = "https://raw.githubusercontent.com/Rose-Petals/TOL-1B/refs/heads/main/TOLCC%20Break%20Through%20Tech%20Dataset%20(1).csv"

df = pd.read_csv(url)
(df.head())

,INTAKE METHOD,REFERENCES,"Please be specific on who sent you our way, we'd like to thank them.",AGE,TOWN,INSURANCE CARRIER,APPOINTMENT LOCATION,APPOINTMENT TYPE,"If Talk Therapy, specifically what type?",Appointment Time,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26
0,Call,Bariatric Doctor,Bariatric Doctor,25-30,Elizabeth,BCBS,Virtual,Talk Therapy,Bariatric Evaluation,Evening (4-8),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Call,Family/Friend,Mom,10-15,Summit,United Healthcare,Virtual,Talk Therapy,Individual (minor),Afternoon (12-4),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Boom Form,Family/Friend,Friend,20-25,Monroe,BCBS,Freehold,Talk Therapy,Individual (adult),Afternoon (12-4),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Boom Form,Family/Friend,NaN,25-30,Ocean,BCBS,Freehold,Talk Therapy,Individual (adult),Afternoon (12-4),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Boom Form,Family/Friend,NaN,30-35,Jackson,Aetna,Freehold,Talk Therapy,Individual (adult),Afternoon (12-4),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [45]:
pd.set_option("display.max_columns", None) ##displays all 27 columns
df.head()

,INTAKE METHOD,REFERENCES,"Please be specific on who sent you our way, we'd like to thank them.",AGE,TOWN,INSURANCE CARRIER,APPOINTMENT LOCATION,APPOINTMENT TYPE,"If Talk Therapy, specifically what type?",Appointment Time,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26
0,Call,Bariatric Doctor,Bariatric Doctor,25-30,Elizabeth,BCBS,Virtual,Talk Therapy,Bariatric Evaluation,Evening (4-8),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Call,Family/Friend,Mom,10-15,Summit,United Healthcare,Virtual,Talk Therapy,Individual (minor),Afternoon (12-4),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Boom Form,Family/Friend,Friend,20-25,Monroe,BCBS,Freehold,Talk Therapy,Individual (adult),Afternoon (12-4),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Boom Form,Family/Friend,NaN,25-30,Ocean,BCBS,Freehold,Talk Therapy,Individual (adult),Afternoon (12-4),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Boom Form,Family/Friend,NaN,30-35,Jackson,Aetna,Freehold,Talk Therapy,Individual (adult),Afternoon (12-4),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
print(df.columns.tolist())

['INTAKE METHOD', ' REFERENCES', "Please be specific on who sent you our way, we'd like to thank them. ", 'AGE', 'TOWN', 'INSURANCE CARRIER', 'APPOINTMENT LOCATION', 'APPOINTMENT TYPE', 'If Talk Therapy, specifically what type?', 'Appointment Time', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26']

In [47]:
df["Unnamed: 10"].value_counts(dropna=False) ##includes NaN

Unnamed: 10
NaN                     1031
Submitted Form             1
503                        1
Start Talk Therapy         1
Start Med Management       1
Name: count, dtype: int64

In [48]:
df["Unnamed: 11"].value_counts(dropna=False) ##includes NaN

Unnamed: 11
NaN      1032
220.0       1
378.0       1
75.0        1
Name: count, dtype: int64

In [49]:
df["Unnamed: 12"].value_counts(dropna=False) ##includes NaN

Unnamed: 12
NaN    1035
Name: count, dtype: int64

In [50]:
empty_cols = df.columns[df.isna().all()]  #checks which columns have all NaN in each
print(empty_cols)

Index(['Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26'],
      dtype='object')

In [51]:
df = df.dropna(axis=1, how="all") ##dropping columns w/ all NaN in each

In [52]:
pd.set_option("display.max_columns", None) ##displays all 27 columns
df.head()

,INTAKE METHOD,REFERENCES,"Please be specific on who sent you our way, we'd like to thank them.",AGE,TOWN,INSURANCE CARRIER,APPOINTMENT LOCATION,APPOINTMENT TYPE,"If Talk Therapy, specifically what type?",Appointment Time,Unnamed: 10,Unnamed: 11
0,Call,Bariatric Doctor,Bariatric Doctor,25-30,Elizabeth,BCBS,Virtual,Talk Therapy,Bariatric Evaluation,Evening (4-8),NaN,NaN
1,Call,Family/Friend,Mom,10-15,Summit,United Healthcare,Virtual,Talk Therapy,Individual (minor),Afternoon (12-4),NaN,NaN
2,Boom Form,Family/Friend,Friend,20-25,Monroe,BCBS,Freehold,Talk Therapy,Individual (adult),Afternoon (12-4),NaN,NaN
3,Boom Form,Family/Friend,NaN,25-30,Ocean,BCBS,Freehold,Talk Therapy,Individual (adult),Afternoon (12-4),NaN,NaN
4,Boom Form,Family/Friend,NaN,30-35,Jackson,Aetna,Freehold,Talk Therapy,Individual (adult),Afternoon (12-4),NaN,NaN

In [53]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")  #standardizing column names
print(df.columns.tolist())

['intake_method', 'references', "please_be_specific_on_who_sent_you_our_way,_we'd_like_to_thank_them.", 'age', 'town', 'insurance_carrier', 'appointment_location', 'appointment_type', 'if_talk_therapy,_specifically_what_type?', 'appointment_time', 'unnamed:_10', 'unnamed:_11']

In [54]:
df.rename(columns={'if_talk_therapy,_specifically_what_type?': 'talk_therapy_type', 'references' : 'referer'}, inplace=True)
df.drop(columns= {"please_be_specific_on_who_sent_you_our_way,_we'd_like_to_thank_them.", "unnamed:_10", "unnamed:_11"}, inplace=True)
df.head()

,intake_method,referer,age,town,insurance_carrier,appointment_location,appointment_type,talk_therapy_type,appointment_time
0,Call,Bariatric Doctor,25-30,Elizabeth,BCBS,Virtual,Talk Therapy,Bariatric Evaluation,Evening (4-8)
1,Call,Family/Friend,10-15,Summit,United Healthcare,Virtual,Talk Therapy,Individual (minor),Afternoon (12-4)
2,Boom Form,Family/Friend,20-25,Monroe,BCBS,Freehold,Talk Therapy,Individual (adult),Afternoon (12-4)
3,Boom Form,Family/Friend,25-30,Ocean,BCBS,Freehold,Talk Therapy,Individual (adult),Afternoon (12-4)
4,Boom Form,Family/Friend,30-35,Jackson,Aetna,Freehold,Talk Therapy,Individual (adult),Afternoon (12-4)

In [55]:
df['talk_therapy_type'].value_counts(dropna=False)

talk_therapy_type
Individual (adult)      593
Individual (minor)      248
NaN                     105
Couples                  57
​                        18
Family                    8
Bariatric Evaluation      6
Name: count, dtype: int64

In [56]:
df['talk_therapy_type'].unique()

array(['Bariatric Evaluation', 'Individual (minor)', 'Individual (adult)',
       nan, 'Couples', 'Family', '\u200b'], dtype=object)

In [57]:
df['talk_therapy_type'] = df['talk_therapy_type'].replace('\u200b', np.nan) #remove 18 hidden character row values w/ NaN
df['talk_therapy_type'].value_counts(dropna=False)

talk_therapy_type
Individual (adult)      593
Individual (minor)      248
NaN                     123
Couples                  57
Family                    8
Bariatric Evaluation      6
Name: count, dtype: int64

In [58]:
df['talk_therapy_type'] = df['talk_therapy_type'].replace('Individual (minor)', 'Individual')
df['talk_therapy_type'] = df['talk_therapy_type'].replace('Individual (adult)', 'Individual')
df['talk_therapy_type'].value_counts(dropna=False)

talk_therapy_type
Individual              841
NaN                     123
Couples                  57
Family                    8
Bariatric Evaluation      6
Name: count, dtype: int64

In [59]:
def average_age(cell):   ##function to average out age instead of having it as a range like 15-20
    if pd.isna(cell):
        return np.nan
    values = str(cell).replace('-', ',').split(',')
    nums = []
    for val in values:
        val = val.strip()
        try:
            nums.append(float(val))
        except ValueError:
            continue
    if not nums:
        return np.nan
    return sum(nums) / len(nums)
df['age'] = df['age'].apply(average_age)
print(df['age'])

0       27.5
1       12.5
2       22.5
3       27.5
4       32.5
        ...
1030     7.5
1031    12.5
1032    17.5
1033    42.5
1034    22.5
Name: age, Length: 1035, dtype: float64

In [60]:
df.head()

,intake_method,referer,age,town,insurance_carrier,appointment_location,appointment_type,talk_therapy_type,appointment_time
0,Call,Bariatric Doctor,27.5,Elizabeth,BCBS,Virtual,Talk Therapy,Bariatric Evaluation,Evening (4-8)
1,Call,Family/Friend,12.5,Summit,United Healthcare,Virtual,Talk Therapy,Individual,Afternoon (12-4)
2,Boom Form,Family/Friend,22.5,Monroe,BCBS,Freehold,Talk Therapy,Individual,Afternoon (12-4)
3,Boom Form,Family/Friend,27.5,Ocean,BCBS,Freehold,Talk Therapy,Individual,Afternoon (12-4)
4,Boom Form,Family/Friend,32.5,Jackson,Aetna,Freehold,Talk Therapy,Individual,Afternoon (12-4)

In [61]:
df['age'].unique()

array([27.5, 12.5, 22.5, 32.5,  nan, 17.5, 62.5, 42.5,  3. ,  7.5, 52.5,
       57.5, 37.5, 67.5, 50. , 30. , 45. , 77.5, 72.5, 82.5, 87.5, 40. ,
       47.5, 60. , 55. , 35. , 25. ])

In [62]:
df['appointment_time'].value_counts()
df['appointment_time'] = df['appointment_time'].replace('Evening (4-8)' , 'Evening')
df['appointment_time'] = df['appointment_time'].replace('Afternoon (12-4)' , 'Afternoon')
df['appointment_time'] = df['appointment_time'].replace('Morning (9-12)' , 'Morning')
df['appointment_time'].value_counts()

appointment_time
Evening      397
Afternoon    397
Morning      240
Name: count, dtype: int64

In [63]:
df.isnull().sum()

intake_method             0
referer                   2
age                       6
town                      4
insurance_carrier         2
appointment_location      1
appointment_type          1
talk_therapy_type       123
appointment_time          1
dtype: int64

In [64]:
df.dropna(subset = ['appointment_time'], inplace = True)

In [65]:
df.isnull().sum()

intake_method             0
referer                   2
age                       6
town                      4
insurance_carrier         2
appointment_location      0
appointment_type          0
talk_therapy_type       122
appointment_time          0
dtype: int64

In [66]:
df.fillna({'age': df['age'].mean(), 'referer': 'Unknown', 'town' : 'Unknown', 'insurance_carrier' : 'Unknown'}, inplace=True)
df.isnull().sum()

intake_method             0
referer                   0
age                       0
town                      0
insurance_carrier         0
appointment_location      0
appointment_type          0
talk_therapy_type       122
appointment_time          0
dtype: int64

In [67]:
df.head()

,intake_method,referer,age,town,insurance_carrier,appointment_location,appointment_type,talk_therapy_type,appointment_time
0,Call,Bariatric Doctor,27.5,Elizabeth,BCBS,Virtual,Talk Therapy,Bariatric Evaluation,Evening
1,Call,Family/Friend,12.5,Summit,United Healthcare,Virtual,Talk Therapy,Individual,Afternoon
2,Boom Form,Family/Friend,22.5,Monroe,BCBS,Freehold,Talk Therapy,Individual,Afternoon
3,Boom Form,Family/Friend,27.5,Ocean,BCBS,Freehold,Talk Therapy,Individual,Afternoon
4,Boom Form,Family/Friend,32.5,Jackson,Aetna,Freehold,Talk Therapy,Individual,Afternoon

In [68]:
df['appointment_type'].unique()

array(['Talk Therapy', 'Medication Management'], dtype=object)

In [69]:
df['talk_therapy_type'] = df['talk_therapy_type'].fillna('ignore')
therapy_dummies = pd.get_dummies(df['talk_therapy_type'], prefix = 'therapy')
therapy_dummies = therapy_dummies[['therapy_Individual', 'therapy_Family', 'therapy_Couples', 'therapy_Bariatric Evaluation']].reindex(df.index,fill_value = 0)
df['Medication Management'] = (df['appointment_type'] == 'Medication Management').astype(int)
df = pd.concat([df, therapy_dummies], axis = 1)
therapy_columns = ['therapy_Individual', 'therapy_Family', 'therapy_Couples', 'therapy_Bariatric Evaluation']
df[therapy_columns] = df[therapy_columns].astype(int)
df.drop(['appointment_type', 'talk_therapy_type'], axis = 1, inplace = True)  ##implemented one hot encoding to see the therapy type easier

In [70]:
df.head()

,intake_method,referer,age,town,insurance_carrier,appointment_location,appointment_time,Medication Management,therapy_Individual,therapy_Family,therapy_Couples,therapy_Bariatric Evaluation
0,Call,Bariatric Doctor,27.5,Elizabeth,BCBS,Virtual,Evening,0,0,0,0,1
1,Call,Family/Friend,12.5,Summit,United Healthcare,Virtual,Afternoon,0,1,0,0,0
2,Boom Form,Family/Friend,22.5,Monroe,BCBS,Freehold,Afternoon,0,1,0,0,0
3,Boom Form,Family/Friend,27.5,Ocean,BCBS,Freehold,Afternoon,0,1,0,0,0
4,Boom Form,Family/Friend,32.5,Jackson,Aetna,Freehold,Afternoon,0,1,0,0,0

In [71]:
from scipy.stats import chi2_contingency

In [72]:
categorical_cols = ['intake_method', 'referer', 'town', 'insurance_carrier',
       'appointment_location', 'Medication Management',
       'therapy_Individual', 'therapy_Family', 'therapy_Couples',
       'therapy_Bariatric Evaluation']

sig_columns = []

for col in categorical_cols:
  contingency_all = pd.crosstab(df[col], df['appointment_time'])
  chi2, p, dof, expected = chi2_contingency(contingency_all)

  print(col)
  print("Chi-square Statistic:", chi2)
  print("p value", p)
  if p<=0.05:
    print('There is a significant association between both groups')
    #unlikely to happen by change, so we reject null and say that there is an association with appointment time
    sig_columns.append(col)
  else:
    print('There is no significance association between groups')
    #this is saying that there is no evidence that the group depends on appointment time

  print('\n')

intake_method
Chi-square Statistic: 6.94120358034161
p value 0.32631893018453484
There is no significance association between groups


referer
Chi-square Statistic: 29.323627350360788
p value 0.20818861633267147
There is no significance association between groups


town
Chi-square Statistic: 425.1888663123823
p value 0.05454280709567423
There is no significance association between groups


insurance_carrier
Chi-square Statistic: 41.655542152482
p value 0.11804666144239613
There is no significance association between groups


appointment_location
Chi-square Statistic: 14.801728437687359
p value 0.005130615558483234
There is a significant association between both groups


Medication Management
Chi-square Statistic: 41.220728563642524
p value 1.119521716348284e-09
There is a significant association between both groups


therapy_Individual
Chi-square Statistic: 26.114981417898083
p value 2.1340463000557865e-06
There is a significant association between both groups


therapy_Family
Chi-square Statistic: 1.9954158554738834
p value 0.36872361451827884
There is no significance association between groups


therapy_Couples
Chi-square Statistic: 0.085916712188306
p value 0.9579512820693921
There is no significance association between groups


therapy_Bariatric Evaluation
Chi-square Statistic: 2.648312387491138
p value 0.2660273399419222
There is no significance association between groups

In [73]:
df['binary_time'] = df['appointment_time']
df['binary_time'] = df['binary_time'].apply(lambda x: 1 if x == 'Morning' else 0)
#this function converts appointment time to binary variable: morning vs not morning

In [74]:
for col in sig_columns:
  contingency_sig = pd.crosstab(df[col], df['binary_time'])
  chi2, p, dof, expected = chi2_contingency(contingency_sig)

  print(col)
  print("Chi-square Statistic:", chi2)
  print("p value", p)
  if p<=0.05:
    print('There is a significant association with Morning time')
    #unlikely to happen by change, so we reject null and say that there is an association with morning time
  else:
    print('There is no significance association with Morning time')
    #this is saying that there is no evidence that the group depends on appointment time

  print('\n')

appointment_location
Chi-square Statistic: 9.56429326380132
p value 0.008377995178936868
There is a significant association with Morning time


Medication Management
Chi-square Statistic: 23.8940292324009
p value 1.0178696986230436e-06
There is a significant association with Morning time


therapy_Individual
Chi-square Statistic: 16.835262844137993
p value 4.076867683488183e-05
There is a significant association with Morning time

In [77]:
import matplotlib.pyplot as plt

times = ['Afternoon', 'Evening', 'Morning']
print(times)

virtual = df[df['appointment_location'] == 'Virtual']

freehold = df[df['appointment_location'] == 'Freehold']
princeton = df[df['appointment_location'] == 'Freehold']

virtual_segment = virtual['appointment_time'].value_counts().sort_index()
freehold_segment = freehold['appointment_time'].value_counts().sort_index()
princeton_segment = princeton['appointment_time'].value_counts().sort_index()

['Afternoon', 'Evening', 'Morning']

In [79]:
from scipy.stats import f_oneway

groups = []
for name, group in df.groupby('binary_time'):
    ages = group['age']
    groups.append(ages)

f, p_val = f_oneway(groups[0],groups[1])
print("F statistic: ", f)
print("p value", p_val)

if p<=0.05:
    print('There is a significant difference with Morning time')
else:
    print('There is no significance difference Morning time')
    #this is saying that there is no evidence that age depends on appointment time

F statistic:  42.26203943434918
p value 1.2408167855511682e-10
There is a significant difference with Morning time